name: ag_test
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #router
  auto_route: ^7.8.4

  #env
  envied: ^0.5.3

  #dependency injection
  get_it: ^7.6.6
  injectable: ^2.3.2

  #state management
  flutter_bloc: ^8.1.3

  #data models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #functional programmings
  fpdart: ^1.1.0

  #network requests
  dio: ^5.3.4

  #logger
  logger: ^2.0.2+1

  infinite_scroll_pagination: ^4.0.0

  #internet checker
  internet_connection_checker: ^1.0.0+1

  #file picker
  file_picker: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  #envs
  envied_generator: ^0.5.1

  #generators
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1

  # route generator
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/hierarchy.json

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/localization/arb
  output_dir: lib/localization/generated
